FROM python:3.12-slim

RUN apt-get update && apt-get install -y curl

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/component_tests/pytest_appium_android_tests
RUN chmod +x component_tests/pytest_appium_android_tests/entrypoint.sh
ENTRYPOINT ["./component_tests/pytest_appium_android_tests/entrypoint.sh"]
