name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Show Docker and Make versions
      run: |
        docker compose version
        make --version

    - name: Run component and unit tests
      run: make ci_parallel_tests
